version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run lint check
          command: npm run lint
      - run:
          name: Build project
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./build/*

  deploy:
    docker:
      - image: 'cimg/python:3.6'
    environment:
      AWS_REGION: "us-east-1"
    steps:
      - attach_workspace:
          at: ~/project
      - aws-s3/sync:
          arguments: --acl public-read --cache-control "no-cache"
          from: ./build/
          to: "s3://backend-api-docs"

workflows:
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
