openapi: 3.0.0
info:
  title: Jira clone
  version: 0.0.1
servers:
  - url: https://9b359ezcwb.execute-api.us-east-1.amazonaws.com
    description: Staging server

components:
  securitySchemes:
    auth_token:
      description: JWT token required for consuming API. Token valid for 100 days
      type: apiKey
      in: header
      name: Authorization

x-tagGroups:
  - name: Users
    tags:
      - Users

paths:
  #Accounts
  /users:
    $ref: ./api/users/users.yaml
